# Stage 1 — Build Angular 17
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --prefer-offline
COPY . .
RUN npm run build

# Stage 2 — Nginx
FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
# outputPath angular.json = dist/socrates-frontend
COPY --from=builder /app/dist/socrates-frontend /usr/share/nginx/html
EXPOSE 80
